### ISSUE TITLE
Error in generating upgradeable contracts using npm module

### ISSUE THREAD

**Issue by Aniket-Engg** [OpenZeppelin/contracts-wizard#182]
This line https://github.com/OpenZeppelin/contracts-wizard/blob/master/packages/core/src/options.ts#L14 throws error for `erc20.print({ ...erc20.defaults, upgradeable: 'uups'})`

Error is:

```
TypeError: path_1.default.parse is not a function
    at upgradeableImport (options.js:17:29)
    at Object.transformImport (options.js:33:1)
    at print.js:16:45
    at Array.map (<anonymous>)
    at printContract (print.js:16:1)
    at Object.printERC20 [as print] (erc20.js:43:1)
    at index.ts:6:40
    at Generator.next (<anonymous>)
    at vendor.0.27.0-dev.1663251417197.js:137866:71
    at new Promise (<anonymous>)
```

**Comment by Aniket-Engg** [comment]
this was resolved on using `path-browserify`
